/*
 * This file is generated by jOOQ.
 */
package com.aitorr.admintelegrambot.infrastructure.jooq


import com.aitorr.admintelegrambot.infrastructure.jooq.tables.ChatBotUsers
import com.aitorr.admintelegrambot.infrastructure.jooq.tables.FlywaySchemaHistory

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.chat_bot_users</code>.
     */
    val CHAT_BOT_USERS: ChatBotUsers get() = ChatBotUsers.CHAT_BOT_USERS

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory get() = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

    public override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    public override fun getTables(): List<Table<*>> = listOf(
        ChatBotUsers.CHAT_BOT_USERS,
        FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
    )
}
