/*
 * This file is generated by jOOQ.
 */
package com.aitorr.admintelegrambot.infrastructure.jooq.tables.daos


import com.aitorr.admintelegrambot.infrastructure.jooq.tables.ChatBotUsers
import com.aitorr.admintelegrambot.infrastructure.jooq.tables.records.ChatBotUsersRecord

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ChatBotUsersDao(configuration: Configuration?) : DAOImpl<ChatBotUsersRecord, com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers, Long>(ChatBotUsers.CHAT_BOT_USERS, com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers::class.java, configuration) {

    /**
     * Create a new ChatBotUsersDao without any configuration
     */
    constructor(): this(null)

    public override fun getId(o: com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetchRange(ChatBotUsers.CHAT_BOT_USERS.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetch(ChatBotUsers.CHAT_BOT_USERS.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers? = fetchOne(ChatBotUsers.CHAT_BOT_USERS.ID, value)

    /**
     * Fetch records that have <code>is_bot BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfIsBot(lowerInclusive: Boolean?, upperInclusive: Boolean?): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetchRange(ChatBotUsers.CHAT_BOT_USERS.IS_BOT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>is_bot IN (values)</code>
     */
    fun fetchByIsBot(vararg values: Boolean): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetch(ChatBotUsers.CHAT_BOT_USERS.IS_BOT, *values.toTypedArray())

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfFirstName(lowerInclusive: String?, upperInclusive: String?): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetchRange(ChatBotUsers.CHAT_BOT_USERS.FIRST_NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    fun fetchByFirstName(vararg values: String): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetch(ChatBotUsers.CHAT_BOT_USERS.FIRST_NAME, *values)

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfLastName(lowerInclusive: String?, upperInclusive: String?): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetchRange(ChatBotUsers.CHAT_BOT_USERS.LAST_NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    fun fetchByLastName(vararg values: String): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetch(ChatBotUsers.CHAT_BOT_USERS.LAST_NAME, *values)

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUsername(lowerInclusive: String?, upperInclusive: String?): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetchRange(ChatBotUsers.CHAT_BOT_USERS.USERNAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    fun fetchByUsername(vararg values: String): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetch(ChatBotUsers.CHAT_BOT_USERS.USERNAME, *values)

    /**
     * Fetch records that have <code>language_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfLanguageCode(lowerInclusive: String?, upperInclusive: String?): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetchRange(ChatBotUsers.CHAT_BOT_USERS.LANGUAGE_CODE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>language_code IN (values)</code>
     */
    fun fetchByLanguageCode(vararg values: String): List<com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers> = fetch(ChatBotUsers.CHAT_BOT_USERS.LANGUAGE_CODE, *values)
}
