/*
 * This file is generated by jOOQ.
 */
package com.aitorr.admintelegrambot.infrastructure.jooq.tables.references


import com.aitorr.admintelegrambot.infrastructure.jooq.tables.ChatBotUsers
import com.aitorr.admintelegrambot.infrastructure.jooq.tables.FlywaySchemaHistory



/**
 * The table <code>public.chat_bot_users</code>.
 */
val CHAT_BOT_USERS: ChatBotUsers = ChatBotUsers.CHAT_BOT_USERS

/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
