/*
 * This file is generated by jOOQ.
 */
package com.aitorr.admintelegrambot.infrastructure.jooq.tables


import com.aitorr.admintelegrambot.infrastructure.jooq.Public
import com.aitorr.admintelegrambot.infrastructure.jooq.indexes.IDX_CHAT_BOT_USERS_USERNAME
import com.aitorr.admintelegrambot.infrastructure.jooq.keys.CHAT_BOT_USERS_PKEY
import com.aitorr.admintelegrambot.infrastructure.jooq.tables.records.ChatBotUsersRecord

import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ChatBotUsers(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, ChatBotUsersRecord>?,
    aliased: Table<ChatBotUsersRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<ChatBotUsersRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.chat_bot_users</code>
         */
        val CHAT_BOT_USERS: ChatBotUsers = ChatBotUsers()
    }

    /**
     * The class holding records for this type
     */
    public override fun getRecordType(): Class<ChatBotUsersRecord> = ChatBotUsersRecord::class.java

    /**
     * The column <code>public.chat_bot_users.id</code>.
     */
    val ID: TableField<ChatBotUsersRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.chat_bot_users.is_bot</code>.
     */
    val IS_BOT: TableField<ChatBotUsersRecord, Boolean?> = createField(DSL.name("is_bot"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>public.chat_bot_users.first_name</code>.
     */
    val FIRST_NAME: TableField<ChatBotUsersRecord, String?> = createField(DSL.name("first_name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.chat_bot_users.last_name</code>.
     */
    val LAST_NAME: TableField<ChatBotUsersRecord, String?> = createField(DSL.name("last_name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.chat_bot_users.username</code>.
     */
    val USERNAME: TableField<ChatBotUsersRecord, String?> = createField(DSL.name("username"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.chat_bot_users.language_code</code>.
     */
    val LANGUAGE_CODE: TableField<ChatBotUsersRecord, String?> = createField(DSL.name("language_code"), SQLDataType.VARCHAR(10), this, "")

    private constructor(alias: Name, aliased: Table<ChatBotUsersRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<ChatBotUsersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.chat_bot_users</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.chat_bot_users</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.chat_bot_users</code> table reference
     */
    constructor(): this(DSL.name("chat_bot_users"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, ChatBotUsersRecord>): this(Internal.createPathAlias(child, key), child, key, CHAT_BOT_USERS, null)
    public override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    public override fun getIndexes(): List<Index> = listOf(IDX_CHAT_BOT_USERS_USERNAME)
    public override fun getPrimaryKey(): UniqueKey<ChatBotUsersRecord> = CHAT_BOT_USERS_PKEY
    public override fun `as`(alias: String): ChatBotUsers = ChatBotUsers(DSL.name(alias), this)
    public override fun `as`(alias: Name): ChatBotUsers = ChatBotUsers(alias, this)
    public override fun `as`(alias: Table<*>): ChatBotUsers = ChatBotUsers(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    public override fun rename(name: String): ChatBotUsers = ChatBotUsers(DSL.name(name), null)

    /**
     * Rename this table
     */
    public override fun rename(name: Name): ChatBotUsers = ChatBotUsers(name, null)

    /**
     * Rename this table
     */
    public override fun rename(name: Table<*>): ChatBotUsers = ChatBotUsers(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    public override fun fieldsRow(): Row6<Long?, Boolean?, String?, String?, String?, String?> = super.fieldsRow() as Row6<Long?, Boolean?, String?, String?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Boolean?, String?, String?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Boolean?, String?, String?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
