/*
 * This file is generated by jOOQ.
 */
package com.aitorr.admintelegrambot.infrastructure.jooq.keys


import com.aitorr.admintelegrambot.infrastructure.jooq.tables.ChatBotUsers
import com.aitorr.admintelegrambot.infrastructure.jooq.tables.FlywaySchemaHistory
import com.aitorr.admintelegrambot.infrastructure.jooq.tables.records.ChatBotUsersRecord
import com.aitorr.admintelegrambot.infrastructure.jooq.tables.records.FlywaySchemaHistoryRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val CHAT_BOT_USERS_PKEY: UniqueKey<ChatBotUsersRecord> = Internal.createUniqueKey(ChatBotUsers.CHAT_BOT_USERS, DSL.name("chat_bot_users_pkey"), arrayOf(ChatBotUsers.CHAT_BOT_USERS.ID), true)
val FLYWAY_SCHEMA_HISTORY_PK: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
