/*
 * This file is generated by jOOQ.
 */
package com.aitorr.admintelegrambot.infrastructure.jooq.tables.records


import com.aitorr.admintelegrambot.infrastructure.jooq.tables.ChatBotUsers

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ChatBotUsersRecord() : UpdatableRecordImpl<ChatBotUsersRecord>(ChatBotUsers.CHAT_BOT_USERS), Record6<Long?, Boolean?, String?, String?, String?, String?> {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsBot")
    open var isBot: Boolean?
        set(value): Unit = set(1, value)
        get(): Boolean? = get(1) as Boolean?

    open var firstName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var lastName: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var username: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var languageCode: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    public override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    public override fun fieldsRow(): Row6<Long?, Boolean?, String?, String?, String?, String?> = super.fieldsRow() as Row6<Long?, Boolean?, String?, String?, String?, String?>
    public override fun valuesRow(): Row6<Long?, Boolean?, String?, String?, String?, String?> = super.valuesRow() as Row6<Long?, Boolean?, String?, String?, String?, String?>
    public override fun field1(): Field<Long?> = ChatBotUsers.CHAT_BOT_USERS.ID
    public override fun field2(): Field<Boolean?> = ChatBotUsers.CHAT_BOT_USERS.IS_BOT
    public override fun field3(): Field<String?> = ChatBotUsers.CHAT_BOT_USERS.FIRST_NAME
    public override fun field4(): Field<String?> = ChatBotUsers.CHAT_BOT_USERS.LAST_NAME
    public override fun field5(): Field<String?> = ChatBotUsers.CHAT_BOT_USERS.USERNAME
    public override fun field6(): Field<String?> = ChatBotUsers.CHAT_BOT_USERS.LANGUAGE_CODE
    public override fun component1(): Long? = id
    public override fun component2(): Boolean? = isBot
    public override fun component3(): String? = firstName
    public override fun component4(): String? = lastName
    public override fun component5(): String? = username
    public override fun component6(): String? = languageCode
    public override fun value1(): Long? = id
    public override fun value2(): Boolean? = isBot
    public override fun value3(): String? = firstName
    public override fun value4(): String? = lastName
    public override fun value5(): String? = username
    public override fun value6(): String? = languageCode

    public override fun value1(value: Long?): ChatBotUsersRecord {
        set(0, value)
        return this
    }

    public override fun value2(value: Boolean?): ChatBotUsersRecord {
        set(1, value)
        return this
    }

    public override fun value3(value: String?): ChatBotUsersRecord {
        set(2, value)
        return this
    }

    public override fun value4(value: String?): ChatBotUsersRecord {
        set(3, value)
        return this
    }

    public override fun value5(value: String?): ChatBotUsersRecord {
        set(4, value)
        return this
    }

    public override fun value6(value: String?): ChatBotUsersRecord {
        set(5, value)
        return this
    }

    public override fun values(value1: Long?, value2: Boolean?, value3: String?, value4: String?, value5: String?, value6: String?): ChatBotUsersRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        return this
    }

    /**
     * Create a detached, initialised ChatBotUsersRecord
     */
    constructor(id: Long? = null, isBot: Boolean? = null, firstName: String? = null, lastName: String? = null, username: String? = null, languageCode: String? = null): this() {
        this.id = id
        this.isBot = isBot
        this.firstName = firstName
        this.lastName = lastName
        this.username = username
        this.languageCode = languageCode
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised ChatBotUsersRecord
     */
    constructor(value: com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos.ChatBotUsers?): this() {
        if (value != null) {
            this.id = value.id
            this.isBot = value.isBot
            this.firstName = value.firstName
            this.lastName = value.lastName
            this.username = value.username
            this.languageCode = value.languageCode
            resetChangedOnNotNull()
        }
    }
}
