/*
 * This file is generated by jOOQ.
 */
package com.aitorr.admintelegrambot.infrastructure.jooq.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class ChatBotUsers(
    var id: Long? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsBot")
    var isBot: Boolean? = null,
    var firstName: String? = null,
    var lastName: String? = null,
    var username: String? = null,
    var languageCode: String? = null
): Serializable {


    public override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: ChatBotUsers = other as ChatBotUsers
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.isBot == null) {
            if (o.isBot != null)
                return false
        }
        else if (this.isBot != o.isBot)
            return false
        if (this.firstName == null) {
            if (o.firstName != null)
                return false
        }
        else if (this.firstName != o.firstName)
            return false
        if (this.lastName == null) {
            if (o.lastName != null)
                return false
        }
        else if (this.lastName != o.lastName)
            return false
        if (this.username == null) {
            if (o.username != null)
                return false
        }
        else if (this.username != o.username)
            return false
        if (this.languageCode == null) {
            if (o.languageCode != null)
                return false
        }
        else if (this.languageCode != o.languageCode)
            return false
        return true
    }

    public override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.isBot == null) 0 else this.isBot.hashCode())
        result = prime * result + (if (this.firstName == null) 0 else this.firstName.hashCode())
        result = prime * result + (if (this.lastName == null) 0 else this.lastName.hashCode())
        result = prime * result + (if (this.username == null) 0 else this.username.hashCode())
        result = prime * result + (if (this.languageCode == null) 0 else this.languageCode.hashCode())
        return result
    }

    public override fun toString(): String {
        val sb = StringBuilder("ChatBotUsers (")

        sb.append(id)
        sb.append(", ").append(isBot)
        sb.append(", ").append(firstName)
        sb.append(", ").append(lastName)
        sb.append(", ").append(username)
        sb.append(", ").append(languageCode)

        sb.append(")")
        return sb.toString()
    }
}
