/*
 * This file is generated by jOOQ.
 */
package com.aitorr.admintelegrambot.infrastructure.jooq.indexes


import com.aitorr.admintelegrambot.infrastructure.jooq.tables.ChatBotUsers
import com.aitorr.admintelegrambot.infrastructure.jooq.tables.FlywaySchemaHistory

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY_S_IDX: Index = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS), false)
val IDX_CHAT_BOT_USERS_USERNAME: Index = Internal.createIndex(DSL.name("idx_chat_bot_users_username"), ChatBotUsers.CHAT_BOT_USERS, arrayOf(ChatBotUsers.CHAT_BOT_USERS.USERNAME), false)
